version: '3.2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always   
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 
    ports:
      - 80:80
      - 443:443   
    networks:      
        - default 
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local    
    ports:
      - 8000:8000
    networks:      
        - default